# -*- coding: utf-8 -*-
"""python_example2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1p9YwqaWe7fpH-Toh7_x28EmDCcKaibTm
"""

import numpy as np
import matplotlib.pyplot as plt

numbers_x = np.random.normal(100, 6.04, 10000)
numbers_y = np.random.normal(100, 6.04, 10000)
plt.hist2d(numbers_x, numbers_y, bins=50, cmap='viridis')
plt.title('random gauss 2d')
plt.xlabel('x', loc = 'right')
plt.ylabel('y', loc = 'top')
plt.colorbar(label='counts')
plt.savefig('canvas2d_py.png')
plt.show()
plt.close()